- country: CO
  parameters:
    bp1: a_schema
    bp2: a_table
    bp3: anotherthing
  pipeline: base_pop
  status: true
- country: CO
  parameters:
    op1: a_schema
    op2: a_table
    op3: somthing
  pipeline: otherpipe
  status: true
- country: CO
  parameters:
    ap1: a_schema
    ap2: a_table
    ap3: smthg
  pipeline: anotherpipe
  status: true
- country: CO
  parameters:
    ap1: a_new_schema
    ap2: a_table
    ap3: smthg
  pipeline: anotherpipe
  status: true
